### ISSUE TITLE
コピーした画像をフォームに貼り付けできない

### ISSUE THREAD

**Issue by nemmysan** [toshiakisp/akahuku-firefox-sp#39]
Firefox最新版107.0（64ビット）にてコピーした画像をフォームに貼り付けられなくなりました。
解決方法があれば教えてください。

**Comment by toshiakisp** [comment]
確認しました。あるスレで原因らしきものを書いてくれてる人が居たので修正できそうです。[https://bugzilla.mozilla.org/show_bug.cgi?id=1797948](https://bugzilla.mozilla.org/show_bug.cgi?id=1797948)

**Comment by nemmysan** [comment]
**ありがとうございます…！**

**Comment by nemmysan** [comment]
更新後、正常に動作することを確認しました。
ご対応いただきありがとうございました。
