### ISSUE TITLE
e10s (multi-process firefox) 対応

### ISSUE THREAD

**Issue by toshiakisp** [toshiakisp/akahuku-firefox-sp#7]
7/18のコミット(https://github.com/toshiakisp/akahuku-firefox-sp/commit/44c5f4e3cf91d4faed29d64af2c9c5c85221c4d1 ... https://github.com/toshiakisp/akahuku-firefox-sp/commit/ca26f4e84501d53566051be98a179bf680ae4bbd )でe10s対応(Fx49~)を一通りdevelopに入れられたけれど、問題はまだ残っている。

**12/08に、確認している問題（下のリスト）は全て対応終了**
**次の sp_rev.44 はようやく全機能がe10s対応済みとなる予定**

- ~~P2Pおそらく全て~~ 単体動作については FIXED f3fbacd766267bf64ff77171c7c88b1f6e304915 
- ~~赤福サイドバーとコンテントドキュメントの連携~~ FIXED 30da3440c4ca08b851b4a4c62a36fde2d231ecc0
- ~~タブソート~~ FIXED f12ecd01a4d2dd8f9d98df2f4071a127b3185553
- 他拡張機能との連携 =>[wiki/CooperationWithExtentions](https://github.com/toshiakisp/akahuku-firefox-sp/wiki/CooperationWithExtentions)で整理中
  - ~~DOMContentLoadedでの動作順序~~ FIXED 2c49c2a
  - ~~スレ・レスの動的追加の通知~~ FIXED 9a81c0641621989f0ad9c7786b02ca6319fed456
  - ~~サイドバーでスレの表示・非表示~~ (これはXUL(メインプロセス)での処理のため問題なかった)
- ~~「スレが消えても表示できるようにする」のバックアップキャッシュを表示できない(キャッシュに.backupが保存はされているが自動では表示されない。https://github.com/toshiakisp/akahuku-firefox-sp/commit/d01e8e06c0107e228f718577141a7e6e2c987f4e のハックの限界)~~ FIXED 05fad731bd30954da07382dbbf2453f4f66df3c8
- ~~「消えそうな画像のキャッシュを保護する」などの、キャッシュ済み画像の管理機能が働かない~~ FIXED 835a52ee7232c154ed97366d12b6bd67b2ff7292, 46c67a4152923f84fe3b5b8332b74d967504f784
- ~~「画像を保存」のポップアップメニューの開く位置がずれてる(制御できない)~~ FIXED 13ac3f3174420757eeba34411c23d35c641ec314
- ~~[50.0a2(security.sandbox.content.level=1)] 画像を保存が失敗するようになった~~ FIXED 487bb51
- ~~[50.0a2(security.sandbox.content.level=1)] MHTで保存が失敗するようになった~~ FIXED 85bcec4
- ~~ChromeプロセスでのgContextMenu.targetのDOM操作で警告"unsafe/forbidden CPOW usage"が大量発生~~ FIXED 9a81c0641621989f0ad9c7786b02ca6319fed456
- ~~[50.0a2?] タイトルを修正(詳細設定)を利用時にページを開くのが異様に遅くなる(数を増やしたカタログで顕著)~~ 50.0 sp_rev.43 で特に問題ないみたい
- ~~オートリンクのプレビューでの通信が匿名化されない~~ FIXED 8972c2eddcae4336fb134a3affb86bb2c3eb6196
- ~~クリップボードからのイメージの貼り付けができない(akahuku-clip-*.jpgを生成できてない)~~ FIXED aacb9b95a3e1a7c29d350e72a89348bc75b626f4
- ~~[sp_rev.43-] ページの情報のメディアプレビューでakahuku*:プロトコルのメディアが見られない~~ FIXED 14a6ec5baa2d601ab68c3aeb96866417dd9e68ed

**Comment by toshiakisp** [comment]
>[50.0a2(security.sandbox.content.level=1)] MHTで保存が失敗するようになった

85bcec4　で修正済

原因：
49では動いていたから見逃していたが、50からプロセスのsandboxingが有効にされはじめたことで(Windows)、コンテンツプロセスのセキュリティが厳しくなったようで、 nsIFileInputStream と nsIFileOutputStream の初期化、 nsIFile.moveTo などがエラーになるようになった。

※security.sandbox.content.level=0とすれば失敗しなくなる

対処：
File I/OはChromeプロセスでのみ行うというFirefoxの方針にしたがって、今回問題になった処理についてもIPC経由でChromeプロセス側のAkahukuで行うようにした。このために使った ipc-stream.jsm (IPC経由でnsI(In|Out)putStreamを操作する)はキャッシュ読み書きように既に実装済みだった。

**Comment by toshiakisp** [comment]
>[50.0a2(security.sandbox.content.level=1)] 画像を保存が失敗するようになった

487bb51で修正済み

問題：
これもまた50.0a2(windows)でのプロセスsandboxingの影響で、WebBrowserPersist.saveURIがリクエストをスタートさせてHTTP 200となっても即？NS_BINDING_ABORTEDに終わるようになった。赤福としては「ファイルがないよ」とエラー表示する。

対処：
はっきりとした原因は不明だが、sandboxingによってファイルを保存するというI/O操作が許可されなくなったためだろうということで、WebBrowserPersistの初期化から保存までをChromeプロセスで行うようにした。
また、内部エラーの類であるのに404時同様に「ファイルがないよ」と表示するのは不正確なので、内部エラーは「保存失敗(HTTP 200)」などと別表示とするようにした。

**Comment by toshiakisp** [comment]
>ChromeプロセスでのgContextMenu.targetのDOM操作で警告"unsafe/forbidden CPOW usage"が大量発生

9a81c0641621989f0ad9c7786b02ca6319fed456 で修正済み。

問題：
コンテクストメニューを表示しようとするたびに、ブラウザコンソールに大量の警告"unsafe/forbidden CPOW usage"が表示されてしまう（動作はする）。これは、コンテクストメニューの popupshowing イベントで走るChromeプロセスのコード(arAkahukuUI.setContextMenu)で、 コンテンツのDOM要素(gContextMenu.target)を操作しようとするたびに生じる。
たぶん50.0a2からこうなった。

e10sでは、ChromeプロセスからでもContentプロセスのものを[CPOW](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Cross_Process_Object_Wrappers)(Cross-Process Object Wrapper)経由で触れる。けれど、この仕組みはあくまでe10s移行支援策で、ほとんどの場合においてパフォーマンスの問題から"unsafe CPOW usage"であると警告される。

対処：
e10s環境下のFirefoxにおける正しいコンテクストメニューの制御の仕方を、[mozilla-central/browser/base/content/content.js](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/content.js) や[sdkの例](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/content/context-menu.js)を参考に取り入れた。
つまり、まずContentプロセスで["content-contextmenu"通知](https://developer.mozilla.org/en-US/docs/Observer_Notifications#Context_menu)を監視し、この通知が来たタイミングでDOM操作等を行って必要な情報を取得してContentプロセスからChromeプロセスへ情報のみを送る。その後、従来通りにChromeプロセスでpopupshowingイベントが生じるので、事前にContentプロセスから送られていた情報(CPOWではない)を参照しながら、コンテキストメニューの項目の表示・非表示を制御する。
これで警告が表示されるようなCPOWの使い方をせずにすむようになる。

**Comment by toshiakisp** [comment]
>[50.0a2?] タイトルを修正(詳細設定)を利用時にページを開くのが異様に遅くなる(数を増やしたカタログで顕著)

問題：
タイトルを修正の詳細設定を有効にしている場合、ページロード後の処理が異様に遅くなることがある。今のところ、カタログモードでのみ確認。カタログの設定で縦横幅を拡張していると実行時間がより長くなる。

タイトルを修正の詳細設定有効時、内部的には XSLTによってタイトル文字列を整形するが、コンテンツプロセスでのタイトル整形部分の DOMParser,XSLTProcessor,XMLSerializer の処理が全部遅くなる。このときにデバッガの呼び出しツリーを見ると、なぜかIPCコールが大量に発生している。意味不明。

**Comment by toshiakisp** [comment]
>「画像を保存」のポップアップメニューの開く位置がずれてる(制御できない)

13ac3f3174420757eeba34411c23d35c641ec314 で解決済

問題：
e10s環境ではコンテンツプロセスが分離されてるため、特定のコンテンツ要素に対してXULのポップアップメニューを開くのに従来の openPopup が使えず、代わりに新しい openPopupAtScreenRect を使う必要があった。そこまでは以前から調査できていたけど、座標が正しく与えられていなかった。縦がおかしかったり、特にウィンドウを最大化してない場合で横に大きくずれてたりした。

対処：
座標系の誤りに気づいてちゃんと対象要素のスクリーン座標を与えることで解決。

**Comment by kartis56** [comment]
e10s 強制オンだと画像貼り付けボタンが押せないですね
browser.tabs.remote.force-enable;true

環境はwin10 pro 64bit、firefox はdeveloper 51.0.a2(2016-10-20) 64bitで上記フラグfalseだと貼り付けできます
プラグインでflashとsilverlight入ってるので試しにe10s強制オンにしていて、貼り付けボタンが押せない状態でした
合間合間とねないこ入れてみて貼り付けできず、e10s強制をオフにしたら押せるようになったのでその二つのアドオン入れてないから張れないのではなく、e10sだろうという感じです

**Comment by kartis56** [comment]
49.0.1で開いて、要素を調査＞akafuku_postform_pastebuttonのとこで
eｖ＞Bubbling やDOM2でソースが見えますが
上記e10sオンにしたdeveloper版ではソースが表示されないので押せないようです

**Comment by toshiakisp** [comment]
> e10s 強制オンだと画像貼り付けボタンが押せないですね

情報感謝です。問題を確認しました：
* **OK** ローカルファイルをコピーしてから貼り付け([貼り付け]ボタン、ペースト(Ctrl-V))
* **NG** イメージ(スクショ等)をコピーしてから貼り付け([貼り付け]ボタン、ペースト(Ctrl-V)) -->機能しない

ファイルがないイメージが貼り付けられた場合には一時ファイル(akahuku-clip-*.jpg)を生成して添付する仕様ですが、e10s環境ではファイル生成が失敗していて、結果「ボタンが押せない」状態になってるっぽい。
(e10s環境の子プロセスではファイル操作が禁止されているので、親プロセスにやらせるよう対処しなければいけない。この部分ではその対処が漏れてた）

developer toolでイベントハンドラのソースが見れないのは関係ないみたい

**Comment by toshiakisp** [comment]
> クリップボードからのイメージの貼り付けができない(akahuku-clip-*.jpgを生成できてない)

aacb9b95a3e1a7c29d350e72a89348bc75b626f4 で解決済

**Comment by kartis56** [comment]
更新お疲れ様です
developer 51.0.a2(2016-11-21) 64bit で rev.43にして確認して見ましたが
akahuku-clip-*.jpgの生成はできていて「ファイルが選択されていません」のままです
いくつか設定変えて再起動して試してみましたが、いずれもTempにakafuku-*jpgは生成されて、ファイル自体は選択されてない状態です
config のフラグオン/オフ（browser.tabs.remote.force-enable)でも、オプションのマルチプロセスオフで試してみて変化なしでした
ここを参考にして http://rockridge.hatenablog.com/entry/2016/07/25/015508 
マルチプロセスオン、browser.tabs.remote.force-enable;true、extensions.e10sBlocksEnablingとextensions.e10sBlockedByAddonsを両方false でも、
逆にマルチプロセスオフ、上記フラグfalse、true、true（これらはおそらく意味ない）でもjpg生成のみでファイル選択されない状態でした

リリース版 50.0（e10sなし)では今まで通り貼り付けできてます

**Comment by kartis56** [comment]
自分の環境かと思って念のためdeveloper に新規プロファイル作って赤福のみ入れ、firefoxのオプションのマルチプロセスオフで再起動して
やっぱりjpg生成のみでファイル選択されない状態でした

**Comment by toshiakisp** [comment]
> P2Pおそらく全て

P2Pの基本動作(ノード登録無し・襲い専状態)については、とりあえずe10s関係のエラーが出ない状態で、画像も見られるように f3fbacd766267bf64ff77171c7c88b1f6e304915　で対応した

**Comment by toshiakisp** [comment]
> developer 51.0.a2(2016-11-21) 64bit で rev.43にして確認して見ましたが
> akahuku-clip-*.jpgの生成はできていて「ファイルが選択されていません」のままです

Developer edition 以降の問題で、e10sは関係ないみたいですね。こういう場合は、良ければ別のIssueとして投稿してもらえると管理しやすいです。

うちの環境 (Windows NT 10.0; Win64; x64)では問題は以下のとおり：
* **OK** release 50.0 (20161104212021)
* **OK** beta 51.0b2 (20161121093909)
* **NG** aurora 52.0a1 (20161122004020)

52.0a1ではブラウザコンソールを見てると、"TypeError: Not enough arguments to File."とエラーが起きてる。

調べたところ、[Bug 1303518](https://bugzilla.mozilla.org/show_bug.cgi?id=1303518)の変更で従来のやり方が不可能になったためみたい。52.0以降に対応したやり方も考慮することで、問題が修正できた：　b361b170e3bbbfa81efad1df5e5e4797e01c9600

**Comment by toshiakisp** [comment]
> 「スレが消えても表示できるようにする」のバックアップキャッシュを表示できない(キャッシュに.backupが保存はされているが自動では表示されない。d01e8e0 のハックの限界)

05fad731bd30954da07382dbbf2453f4f66df3c8 で修正

やっつけハックをもう少しちゃんと書き直した。

**Comment by toshiakisp** [comment]
> 「消えそうな画像のキャッシュを保護する」などの、キャッシュ済み画像の管理機能が働かない(Akahuku.Cache.CachedImageReserverをコンテントプロセスではなくChromeプロセスで動かさないといけない)

46c67a4152923f84fe3b5b8332b74d967504f784 で修正

e10s対応済みのコードを呼びだすようにして修正。

**Comment by toshiakisp** [comment]
> 赤福サイドバーとコンテントドキュメントの連携

20c02c7e237d062c6dbe4ea1600a3d4dcac349a1, ca2cb36c2ef438db441f564d8bd0d6e045344e59, 30da3440c4ca08b851b4a4c62a36fde2d231ecc0 で対応

**Comment by toshiakisp** [comment]
> [sp_rev.43-] ページの情報のメディアプレビューでakahuku*:プロトコルのメディアが見られない

14a6ec5baa2d601ab68c3aeb96866417dd9e68ed で修正

**Comment by toshiakisp** [comment]
リストに入れていなかったけど、オートリンクプレビューのロードに失敗したとき(404 Not Foundなど)に、そのエラーステータスを監視して「ファイルがないよ」等と表示する仕組みが、e10s環境だと詳細なエラーが拾えない問題があった。

4ceedb4e9ee86b7c23292b52cc10d4ce9fc7322b (depends on f5e148f4b3533d00e0779ff253513d59eb774dee, 32c8d8c61584293704062af5a82561938a440923) で修正

**Comment by toshiakisp** [comment]
> オートリンクのプレビューでの通信が匿名化されない

e10s下では、オートリンクのプレビューのための通信はリファラは送信させないで行えていたが、クッキーの送受信のブロックができてなかった。

8972c2eddcae4336fb134a3affb86bb2c3eb6196 で修正

**Comment by toshiakisp** [comment]
sp_rev.44リリースしたのでとりあえずこの件はclosed.
